### ISSUE TITLE
unsolved dependencies

### ISSUE THREAD

**Issue by shainaraza** [jaywonchung/BERT4Rec-VAE-Pytorch#1]
can you help in solving the dependencies

**Comment by jaywonchung** [comment]
Python package dependencies are listed in `requirements.txt`. Perhaps, is there something missing?

**Comment by shainaraza** [comment]
hi thanks for reply
I am unable to work on torch in windows,
please guide

**Comment by jaywonchung** [comment]
Generally, you first want to install "Anaconda" on your system. Then create an Anaconda environment, and install pytorch in that environment with the command `conda install -c pytorch pytorch torchvison`. You will also need to install CUDA on your system to utilize NVIDIA GPUs for computation. Configuring a deep learning environment is well documented in various sources on google, so you'll be able to find more detailed guides there. 

I'll close this issue since this is not an issue of this repository, but a general question whose answer is better addressed through searching. Feel free to reopen if you encounter further issues regarding the package dependency of this repo.

**Comment by shainaraza** [comment]
thanks

**Comment by shainaraza** [comment]
thanks, for yours help, the project running fine on Google Colab
